version: '3'
services:

  postgres:
    extends:
      file: ../common/docker-compose.common.yml
      service: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: ormponder-postgres-testnets

  proxy:
    image: nginx:1.27-alpine
    container_name: ormponder-proxy
    restart: always
    depends_on:
      - ormponder-arbitrum-sepolia
      - ormponder-koi
      - ormponder-pangoro
      - ormponder-sepolia
      - ormponder-taiko-hekla
      - ormponder-tron-shasta
    volumes:
      - "../proxy:/etc/nginx/conf.d"
    ports:
      - 42068:80

  ormponder-arbitrum-sepolia:
    extends:
      file: ../common/docker-compose.common.yml
      service: ormponder-runner
    container_name: ormponder-arbitrum-sepolia
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ormponder_arbitrum_sepolia
    command: ["/app/ponder.sh", "arbitrum_sepolia", "start"]

  ormponder-koi:
    extends:
      file: ../common/docker-compose.common.yml
      service: ormponder-runner
    container_name: ormponder-koi
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ormponder_koi
    command: ["/app/ponder.sh", "koi", "start"]

  ormponder-pangoro:
    extends:
      file: ../common/docker-compose.common.yml
      service: ormponder-runner
    container_name: ormponder-pangoro
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ormponder_pangoro
    command: ["/app/ponder.sh", "pangoro", "start"]

  ormponder-sepolia:
    extends:
      file: ../common/docker-compose.common.yml
      service: ormponder-runner
    container_name: ormponder-sepolia
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ormponder_sepolia
    command: ["/app/ponder.sh", "sepolia", "start"]

  ormponder-taiko-hekla:
    extends:
      file: ../common/docker-compose.common.yml
      service: ormponder-runner
    container_name: ormponder-taiko-hekla
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ormponder_taiko_hekla
    command: ["/app/ponder.sh", "taiko_hekla", "start"]

  ormponder-tron-shasta:
    extends:
      file: ../common/docker-compose.common.yml
      service: ormponder-runner
    container_name: ormponder-tron-shasta
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ormponder_tron_shasta
    command: ["/app/ponder.sh", "tron_shasta", "start"]

