version: '3.9'

services:
  postgres:
    container_name: ormponder-postgres
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  ormponder-runner:
    container_name: ormponder-runner
    image: node:22-alpine
    restart: always
    depends_on:
      - postgres
    volumes:
      - ../:/app
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/postgres


